language: ruby
addons:
  code_climate:
    repo_token: f5092ab344fac7f2de9d7332e00597642a4d24e3d560f7d7f329172a2e5a2def
install:
  - echo openssl_url=https://www.openssl.org/source >> $rvm_path/user/db
  - echo openssl_version=1.0.2d >> $rvm_path/user/db
  - rvm pkg install openssl
  - $rvm_path/usr/bin/openssl version
  - rvm install 2.3-head --with-openssl-dir=$rvm_path/usr
  - rvm use 2.3-head
  - bundle install
script:
  - bundle exec rake test
