language: ruby
install:
  - rvm install ruby-2.4.0
  - rvm use ruby-2.4.0
  - curl -s https://www.openssl.org/source/openssl-1.1.0c.tar.gz | tar xzvf -
  - (cd openssl-1.1.0c && ./config --prefix=$HOME/openssl -Wl,-rpath=$HOME/openssl/lib && make -j8 && make install_sw)
  - $HOME/openssl/bin/openssl version
  - gem install openssl http_parser.rb rack test-unit -- --with-openssl-dir=$HOME/openssl
  - ruby -e'gem "openssl"; require "openssl"; p OpenSSL::OPENSSL_LIBRARY_VERSION'
script:
  - rake test
