language: ruby
install:
  - openssl version
  - rvm pkg install openssl
  - rvm install 2.2.2-alpn --patch https://gist.githubusercontent.com/rhenium/b1711edcc903e8887a51/raw/2309e469f5a3ba15917d804ac61b19e62b3d8faf/ruby-openssl-alpn-no-tests-and-docs.patch --with-openssl-dir=$rvm_path/usr
  - rvm use 2.2.2-alpn
  - bundle install
script:
  - bundle exec rake test
